---
title: "CheapMass"
output: html_document
author: "Alain Duplan & Ariel Lutati"
---


```{r}
library(readxl)
library(TTR)
library(forecast)
library(tree)
library(randomForest)
library(janitor)
```
```{r}
CashFlows <- read_excel("UMass Balance sheets.xlsx", sheet = 1)
#CashFlows <- as.data.frame(t(CashFlows))
original <- CashFlows
tuition <- CashFlows[c(2,18),]
names(CashFlows)
CashFlows <- subset(CashFlows, Nets == "1")
CashFlows <- rbind(CashFlows, tuition)
```

```{r}
train <- CashFlows[,2:4]
test <- CashFlows[,c(5:6)]
train <- as.data.frame(t(train))
test <- as.data.frame(t(test))
```
```{r}
seed.val <- 1234567
set.seed(seed.val)
```

```{r}
<<<<<<< HEAD
x <- original[c(2,16:20),]
x.train <- x[,2:4]
x.train <- as.data.frame(t(x.train))
fit.x <- lm(V1~.,data=x.train)
summary(fit.x)
```

```{r}
fit.1 <- lm(V12 ~V1, data = train)
summary(fit.1)

fit.2 <- lm(V12 ~V2, data = train)
summary(fit.2)

fit.3 <- lm(V12 ~V3, data = train)
summary(fit.3)

fit.4 <- lm(V12 ~V4, data = train)
summary(fit.4)

fit.5 <- lm(V12 ~V5, data = train)
summary(fit.5)

fit.6 <- lm(V12 ~V6, data = train)
summary(fit.6)

fit.7 <- lm(V12 ~V7, data = train)
summary(fit.7)

fit.8 <- lm(V12 ~V8, data = train)
summary(fit.8)

fit.9 <- lm(V12 ~V9, data = train)
summary(fit.9)

fit.10 <- lm(V12 ~V10, data = train)
summary(fit.10)

fit.11 <- lm(V12 ~V11, data = train)
summary(fit.11)

fit.13 <- lm(V12 ~V13, data = train)
summary(fit.13)
=======
train.forest <- randomForest(V12 ~.,data = train, mtry  = 4, importance = T)
#varImpPlot(train.forest)
train.pred <- predict(train.forest, train)
train.forest.pred.ts <- ts((as.numeric(as.vector(train.pred))), frequency = 1, start = c(2015, 1))
train.ts <- ts((as.numeric(as.vector(train$V12))), frequency = 1, start = c(2015, 1))

ts.plot(train.forest.pred.ts, train.ts, gpars = list(col=rainbow(2))) 
legend("topright", legend = c("predictions", "true"), col = rainbow((2)), lty = 1)
>>>>>>> 0c3aca7fbea15844a3175062493a28c43673a503
```

```{r}
#par(mfrow= c(1,2))
train.rmse <- rmse(train$V12, train.pred)
#23,161,920.7
train.res = train.pred - train$V12

train.res.ts <- ts((as.numeric(as.vector(train.res))), frequency = 1, start = c(2015, 1))
ts.plot(train.res.ts, xlab = "Year", ylab = "Cost in $", main = "residuals")

hist(train.res)
```